### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by 1Luc1** [1Luc1/OpenCourier#1]
Hey,

want to ask if this repo is still active? Still I'm planing to make an open courier software and want to know if you have something to share with?

cheers, Luc

**Comment by janissary** [comment]
Hey Luc,

Unfortunately I never started the open source courier software I was
planning, so there's no code for the project.

If you want the repo name transferred over to you happy to do so if you
wish.

..Brendan

**Comment by 1Luc1** [comment]
Hey Brendan,

thanks for you reply. I'm still at the beginning of the development, but
I'm willing to do this one, so yea transfering the repo name would be nice!

Thanks,
Luc

2018-05-09 7:13 GMT+02:00 Bren <notifications@github.com>:

> Hey Luc,
>
> Unfortunately I never started the open source courier software I was
> planning, so there's no code for the project.
>
> If you want the repo name transferred over to you happy to do so if you
> wish.
>
> ..Brendan
>
>
>

**Comment by janissary** [comment]
There you go. Enjoy.

I'm not in the courier business anymore, but if you get to a beta stage at
some point, I'd love to hear how the project is going.

All the best.

**Comment by 1Luc1** [comment]
Thanks!
Yea i will keep you informed!

cheers,
Luc

2018-05-09 7:35 GMT+02:00 Bren <notifications@github.com>:

> There you go. Enjoy.
>
> I'm not in the courier business anymore, but if you get to a beta stage at
> some point, I'd love to hear how the project is going.
>
> All the best.
>
>
>
>
